on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
      trigger_release:
        description: "Tag and trigger release manually"
        required: false
        default: true

name: Tag and Release on PR Merge

jobs:
  test:
    name: release-tag
    uses: kubewarden/github-actions/.github/workflows/reusable-release-tag.yml@acb006fafe5e4da789055f573d11cea2917de59a # v4.5.8
